name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push'
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: deployment check
        uses: github/branch-deploy@v8.2.0
        id: deployment-check
        with:
          merge_deploy_mode: "true"
          environment: production

      - name: checkout
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: actions/checkout@v4

      - name: ssh remote deploy
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: appleboy/ssh-action@2451745138b602d3e100a6def50c8e4e39591d4c # pin@v1.0.2
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DISCORD_TOKEN,YOUTUBE_API_KEY,SPOTIFY_CLIENT_ID,SPOTIFY_CLIENT_SECRET
          script_stop: true
          script: ~/muse/script/deploy -r="main" -d="muse"
